### ISSUE TITLE
SSL hanshake failure

### ISSUE THREAD

**Issue by Percent01** [maurosoria/dirs3arch#7]
I get this error message some target hosts on kali x86
Linux XXX 3.12-kali1-686-pae #1 SMP Debian 3.12.6-2kali1 (2014-01-06) i686 GNU/Linux
Python3 lib installed and run as sudo. 

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "dirs3arch.py", line 36, in <module>
    main = Program()
  File "dirs3arch.py", line 32, in __init__
    self.controller = Controller(self.script_path, self.arguments, self.output)
  File "/root/dirs3arch/dirs3arch/lib/controller/Controller.py", line 59, in __init__
    self.wait()
  File "/root/dirs3arch/dirs3arch/lib/controller/Controller.py", line 199, in wait
    self.fuzzer.start()
  File "/root/dirs3arch/dirs3arch/lib/core/Fuzzer.py", line 75, in start
    self.testersSetup()
  File "/root/dirs3arch/dirs3arch/lib/core/Fuzzer.py", line 54, in testersSetup
    self.testers['/'] = NotFoundTester(self.requester, '{0}/'.format(self.testFailPath))
  File "/root/dirs3arch/dirs3arch/lib/core/NotFoundTester.py", line 31, in __init__
    if self.testNotFoundStatus():
  File "/root/dirs3arch/dirs3arch/lib/core/NotFoundTester.py", line 37, in testNotFoundStatus
    response = self.requester.request(self.notFoundPath)
  File "/root/dirs3arch/dirs3arch/lib/connection/Requester.py", line 114, in request
    assert_same_host=False)
  File "/root/dirs3arch/dirs3arch/thirdparty/urllib3/connectionpool.py", line 502, in urlopen
    raise SSLError(e)
thirdparty.urllib3.exceptions.SSLError: [Errno 1] _ssl.c:392: error:14094410:SSL routines:SSL3_READ_BYTES:sslv3 alert handshake failure

**Comment by maurosoria** [comment]
Hi Percent01, thank you for your feedback

I'll be patching this issue in the next release (next week).

Thanks

**Comment by S0ykot** [comment]
Traceback (most recent call last):
  File "/root/dirsearch/thirdparty/requests/packages/urllib3/connectionpool.py", line 544, in urlopen
    body=body, headers=headers)
  File "/root/dirsearch/thirdparty/requests/packages/urllib3/connectionpool.py", line 341, in _make_request
    self._validate_conn(conn)
  File "/root/dirsearch/thirdparty/requests/packages/urllib3/connectionpool.py", line 761, in _validate_conn
    conn.connect()
  File "/root/dirsearch/thirdparty/requests/packages/urllib3/connection.py", line 238, in connect
    ssl_version=resolved_ssl_version)
  File "/root/dirsearch/thirdparty/requests/packages/urllib3/util/ssl_.py", line 279, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/lib/python3.2/ssl.py", line 189, in wrap_socket
    _context=self)
  File "/usr/lib/python3.2/ssl.py", line 276, in __init__
    raise x
  File "/usr/lib/python3.2/ssl.py", line 272, in __init__
    self.do_handshake()
  File "/usr/lib/python3.2/ssl.py", line 451, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [Errno 8] _ssl.c:392: EOF occurred in violation of protocol

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/dirsearch/thirdparty/requests/adapters.py", line 368, in send
    timeout=timeout
  File "/root/dirsearch/thirdparty/requests/packages/urllib3/connectionpool.py", line 574, in urlopen
    raise SSLError(e)
thirdparty.requests.packages.urllib3.exceptions.SSLError: [Errno 8] _ssl.c:392: EOF occurred in violation of protocol

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/dirsearch/lib/connection/Requester.py", line 132, in request
    headers=headers, timeout=self.timeout)
  File "/root/dirsearch/thirdparty/requests/sessions.py", line 482, in get
    return self.request('GET', url, **kwargs)
  File "/root/dirsearch/thirdparty/requests/sessions.py", line 470, in request
    resp = self.send(prep, **send_kwargs)
  File "/root/dirsearch/thirdparty/requests/sessions.py", line 578, in send
    r = adapter.send(request, **kwargs)
  File "/root/dirsearch/thirdparty/requests/adapters.py", line 426, in send
    raise SSLError(e, request=request)
thirdparty.requests.exceptions.SSLError: [Errno 8] _ssl.c:392: EOF occurred in violation of protocol

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.2/threading.py", line 740, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.2/threading.py", line 693, in run
    self._target(*self._args, **self._kwargs)
  File "/root/dirsearch/lib/core/Fuzzer.py", line 134, in thread_proc
    status, response = self.scan(path)
  File "/root/dirsearch/lib/core/Fuzzer.py", line 109, in scan
    response = self.requester.request(path)
  File "/root/dirsearch/lib/connection/Requester.py", line 139, in request
    except ConnectionResetError as e:
NameError: global name 'ConnectionResetError' is not defined




I'm facing this problem.

**Comment by smartmadre** [comment]
Might be useful for others..
https://github.com/requests/requests/issues/606#issuecomment-435639611
